from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable, Protocol

from erc_engine.domain.models import Conversation, GenerationUsage, PipelineResult


class DatasetPort(Protocol):
    labels: tuple[str, ...]

    def load(self, path: Path, limit: int = 0) -> list[Conversation]: ...
    def normalize_label(self, value: Any, default: str = "neutral") -> str: ...


class JsonModelPort(Protocol):
    def complete(self, prompt: str, step: str) -> dict[str, Any]: ...
    def reset_usage(self) -> None: ...
    def usage(self) -> list[GenerationUsage]: ...
    def absorb_usage(self, entries: Iterable[GenerationUsage]) -> None: ...


class PromptPort(Protocol):
    def baseline(self, conversation: Conversation) -> str: ...
    def appraisal(self, conversation: Conversation) -> str: ...
    def agent(self, conversation: Conversation, assignments: dict[str, Any], module: str) -> str: ...


class PriorPort(Protocol):
    def predict(self, assignments: dict[str, Any]) -> dict[str, Any]: ...


class ResultRepositoryPort(Protocol):
    def completed_ids(self) -> set[str]: ...
    def append(self, results: list[PipelineResult]) -> None: ...
    def read(self) -> Any: ...

